### ISSUE TITLE
[BUG] Erro while try delete cdn

### ISSUE THREAD

**Issue by eufelipemateus** [eufelipemateus/laravel-iptv-channels#14]
**Describe the bug**
Error when trying to delete an cdn that is associated with a user is giving error 500

**To Reproduce**
1. Go to 'https://iptv-cms.felipemateus.com/cdn/list'
2. Click on 'delete'

**Expected behavior**
It is expected to delete the cdn or the delete button does not  show up.

**Screenshots**
![Captura de tela de 2023-03-05 07-56-47](https://user-images.githubusercontent.com/18071941/222956557-05e207ff-e3e4-4622-8c6b-f8dd460e598a.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browse: Chrome and Brave

**Comment by 3v3rm4rt3lL** [comment]
Hello, I really noob in this language or app, could you help me to some steps to getting work? Thanks.

**Comment by eufelipemateus** [comment]
this will fix #15
